### PR TITLE
feat(ui): TE-1068 added sidebar link to swagger

### PR DESCRIPTION
**Pull request by alcatraz627**
#### Issue(s)

[TE-1068](https://cortexdata.atlassian.net/browse/TE-1068)

#### Description

- Added swagger link to sidebar

#### Screenshots

Screenshot_150592372

#### ToDo
- [x] Add sidebar link
- [ ] <strike>Automatically add auth token in swagger</strike> moved to [TE-1104](https://cortexdata.atlassian.net/browse/TE-1104)

### CODE REVIEW

**Comment by alcatraz627** [comment]
Screenshot_150592366

@spham92 this is the setup required to verify this on local, but is totally redundant on the deployment. Should I push this into the codebase?

**Comment by spham92** [comment]
> 

Yeah let's add it

**Comment by spham92** [comment]
Let's actually have the swagger navigation item at the bottom group instead of the top

**Comment by alcatraz627** [comment]
@spham92 moved the swagger link to the bottom section

**Review by spham92 — APPROVED** [review]

**Pull request merged**
