### PR TITLE
feat(ui): TE-2531 update workspace selector

### PR DESCRIPTION
**Pull request by nalin-patidar**
#### Issue(s)

https://startree.atlassian.net/browse/TE-2531

#### Description

Allow user to search for a workspace and also the option to click and copy the workspace name.

https://github.com/user-attachments/assets/dd6422b5-bfe0-4cae-a2a8-5f423f92ffe9

Updated design

https://github.com/user-attachments/assets/7bc5be60-a4db-47eb-959e-5bb8280bfb3d

### CODE REVIEW

**Review by cyrilou242 — CHANGES_REQUESTED** [review]
can we have the same UX as other apps? 

mixing the current namespace and the search bar is confusing
- the behavior is not clear if someone starts to type clicks out of the dropdown (2 cases: current text typed is a valid namespace or not) 
- deleting manually the current workspace is strange and it makes the feature less discoverable

a search input box is explicit
Screenshot 2024-11-20 at 19 27 05

**Comment by nalin-patidar** [comment]
@cyrilou242 Updated the design Please have a look at the attached screen record.

**Comment by anshul98ks123** [comment]
Still looks a lot different than other Apps
can we use the exact same UI component that they're using?

Query Console:
https://celyui.cp.s7e.startree-staging.cloud/query-console/query
Screenshot 2024-11-25 at 2 01 56 PM

Data Manager:
https://data.celyui.cp.s7e.startree-staging.cloud/overview
Screenshot 2024-11-25 at 2 02 16 PM

**Comment by nalin-patidar** [comment]
> Still looks a lot different than other Apps can we use the exact same UI component that they're using?
> 
> Query Console: https://celyui.cp.s7e.startree-staging.cloud/query-console/query Screenshot 2024-11-25 at 2 01 56 PM
> 
> Data Manager: https://data.celyui.cp.s7e.startree-staging.cloud/overview Screenshot 2024-11-25 at 2 02 16 PM

Ux wise its the same. If i will follow the same UI, the header will look unnecessarily bigger. Hence have kept it a bit aligned with TE UI

**Review by cyrilou242 — APPROVED** [review]
LGTM thanks!

**Comment by cyrilou242** [comment]
merging to share with a customer

**Pull request merged**
